// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"pekabeta/internal/application"
	"pekabeta/internal/infrastructure/persistence"
	"pekabeta/internal/interfaces/rest"
)

// Injectors from wire.go:

func CreateApi(db *gorm.DB) *rest.Api {
	customerRepository := persistence.NewCustomerRepository(db)
	customerInteractor := application.NewCustomerInteractor(customerRepository)
	productRepository := persistence.NewProductRepository(db)
	productInteractor := application.NewProductInteractor(productRepository)
	orderRepository := persistence.NewOrderRepository(db)
	orderInteractor := application.NewOrderInteractor(orderRepository)
	invoiceRepository := persistence.NewInvoiceRepository(db)
	invoiceInteractor := application.NewInvoiceInteractor(invoiceRepository)
	api := rest.NewApi(customerInteractor, productInteractor, orderInteractor, invoiceInteractor)
	return api
}

// wire.go:

var repositorySet = wire.NewSet(persistence.NewCustomerRepository, persistence.NewProductRepository, persistence.NewOrderRepository, persistence.NewInvoiceRepository)
