get:
  summary: Retrieve all available products.
  description: Used to retrieve all available products.
  operationId: RetrieveProducts
  responses:
    200:
      $ref: "../../components/responses.yaml#/ProductsResponse"
    401:
      $ref: "../../components/responses.yaml#/Unauthenticated"
    403:
      $ref: "../../components/responses.yaml#/Unauthorized"
    404:
      $ref: "../../components/responses.yaml#/NotFound"
    500:
      $ref: "../../components/responses.yaml#/InternalServerError"