version: "3"

services:
  database:
    container_name: mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test_pekabeta
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 6603:3306
  server:
    container_name: api
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/app
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database