openapi: "3.0.0"
info:
  title: PEKABETA Food Shop API
  version: 1.0.0
  contact:
    name: Aleksandar Rakić
    email: aleksandar.rakic@yahoo.com
servers:
  - url: "http://localhost:3000/api/1.0"
    description: Server description.
paths:
  /sign-in:
    $ref: "./routes/customer/login.yaml"
  /sign-up:
    $ref: "./routes/customer/customer.yaml"
  /customer/modify/{id}:
    $ref: "./routes/customer/customer_edit.yaml"
  /customer/validate/email/{email}:
    $ref: "./routes/customer/customer_validate_email.yaml"
  /customer/validate/phone-number/{phone}:
    $ref: "./routes/customer/customer_validate_phone_number.yaml"
  /product:
    $ref: "./routes/product/product.yaml"
  /product/{id}:
    $ref: "./routes/product/product_edit.yaml"
  /product/filter/product-group/{group}:
    $ref: "./routes/product/product_filter_product_group.yaml"
  /order:
    $ref: "./routes/order/order.yaml"
  /order/{id}:
    $ref: "./routes/order/order_edit.yaml"
  /invoice:
    $ref: "./routes/invoice/invoice.yaml"
  /invoice/{id}:
    $ref: "./routes/invoice/invoice_edit.yaml"