// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"net/http"
	"strings"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Modify customer.
	// (PATCH /customer/modify/{id})
	ModifyCustomer(ctx echo.Context, id Id) error
	// Check if email exists in database.
	// (GET /customer/validate/email/{email})
	ValidateEmail(ctx echo.Context, email Email) error
	// Check if phone number exists in database.
	// (GET /customer/validate/phone-number/{phone})
	ValidatePhoneNumber(ctx echo.Context, phone Phone) error
	// Retrieve invoices.
	// (GET /invoice)
	RetrieveInvoices(ctx echo.Context) error
	// Create invoice.
	// (POST /invoice)
	CreateInvoice(ctx echo.Context) error
	// Retrieve invoice.
	// (GET /invoice/{id})
	RetrieveInvoice(ctx echo.Context, id Id) error
	// Retrieve orders.
	// (GET /order)
	RetrieveOrders(ctx echo.Context) error
	// Create order.
	// (POST /order)
	CreateOrder(ctx echo.Context) error
	// Retrieve order.
	// (GET /order/{id})
	RetrieveOrder(ctx echo.Context, id Id) error
	// Retrieve all available products.
	// (GET /product)
	RetrieveProducts(ctx echo.Context) error
	// Retrieve product details for specified product group.
	// (GET /product/filter/product-group/{group})
	RetrieveProductsByProductGroup(ctx echo.Context, group Group) error
	// Retrieve product details.
	// (GET /product/{id})
	RetrieveProduct(ctx echo.Context, id Id) error
	// Login customer.
	// (POST /sign-in)
	CustomerLogin(ctx echo.Context) error
	// Customer registration.
	// (POST /sign-up)
	CustomerRegistration(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ModifyCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) ModifyCustomer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ModifyCustomer(ctx, id)
	return err
}

// ValidateEmail converts echo context to params.
func (w *ServerInterfaceWrapper) ValidateEmail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "email" -------------
	var email Email

	err = runtime.BindStyledParameter("simple", false, "email", ctx.Param("email"), &email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ValidateEmail(ctx, email)
	return err
}

// ValidatePhoneNumber converts echo context to params.
func (w *ServerInterfaceWrapper) ValidatePhoneNumber(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "phone" -------------
	var phone Phone

	err = runtime.BindStyledParameter("simple", false, "phone", ctx.Param("phone"), &phone)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter phone: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ValidatePhoneNumber(ctx, phone)
	return err
}

// RetrieveInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveInvoices(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RetrieveInvoices(ctx)
	return err
}

// CreateInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInvoice(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateInvoice(ctx)
	return err
}

// RetrieveInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveInvoice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RetrieveInvoice(ctx, id)
	return err
}

// RetrieveOrders converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveOrders(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RetrieveOrders(ctx)
	return err
}

// CreateOrder converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrder(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateOrder(ctx)
	return err
}

// RetrieveOrder converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveOrder(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RetrieveOrder(ctx, id)
	return err
}

// RetrieveProducts converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveProducts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RetrieveProducts(ctx)
	return err
}

// RetrieveProductsByProductGroup converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveProductsByProductGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "group" -------------
	var group Group

	err = runtime.BindStyledParameter("simple", false, "group", ctx.Param("group"), &group)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter group: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RetrieveProductsByProductGroup(ctx, group)
	return err
}

// RetrieveProduct converts echo context to params.
func (w *ServerInterfaceWrapper) RetrieveProduct(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RetrieveProduct(ctx, id)
	return err
}

// CustomerLogin converts echo context to params.
func (w *ServerInterfaceWrapper) CustomerLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CustomerLogin(ctx)
	return err
}

// CustomerRegistration converts echo context to params.
func (w *ServerInterfaceWrapper) CustomerRegistration(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CustomerRegistration(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.PATCH("/customer/modify/:id", wrapper.ModifyCustomer)
	router.GET("/customer/validate/email/:email", wrapper.ValidateEmail)
	router.GET("/customer/validate/phone-number/:phone", wrapper.ValidatePhoneNumber)
	router.GET("/invoice", wrapper.RetrieveInvoices)
	router.POST("/invoice", wrapper.CreateInvoice)
	router.GET("/invoice/:id", wrapper.RetrieveInvoice)
	router.GET("/order", wrapper.RetrieveOrders)
	router.POST("/order", wrapper.CreateOrder)
	router.GET("/order/:id", wrapper.RetrieveOrder)
	router.GET("/product", wrapper.RetrieveProducts)
	router.GET("/product/filter/product-group/:group", wrapper.RetrieveProductsByProductGroup)
	router.GET("/product/:id", wrapper.RetrieveProduct)
	router.POST("/sign-in", wrapper.CustomerLogin)
	router.POST("/sign-up", wrapper.CustomerRegistration)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaTXPbvBH+Kxi0h3aGEeXGPVSn2qnfjuf9SMaOe8l4NDC5khCBAAOAShWNzv1j/WEd",
	"LPgpUhKpyn4P9kkiCGAX+zy7WCy4oZFKUiVBWkMnG5oyzRKwoPEJEsaF+xODiTRPLVeSTuiNaybMkJTZ",
	"xYgGlLtW90ADKlkCdJIPDaiGbxnXENOJ1RkE1EQLSJibc6Z0wmytq12nbqSxmss53W4DOtcqS9vyP2kV",
	"Z5El+PqIHn6KQ3q0xfK4LfMOIqVjwmPyp4eH23/8+YhYHvdbe5Zhz7YO6UJJ6Fi6ayYyS55AH1HBzzBk",
	"5VvfGYy9VjEHpMCHzFiVgP5Fzbm8829de6SkBYl/WZoKHjGnYfjVODU3NSF/1DCjE/qHsCJa6N+aECet",
	"BFdaboNS8LllFvPuEXsrV4pHcG6p+bR7hH7U8fkXipN2CsQWkyppPMbXLD638ButVS68SeBrFpOcZNSh",
	"rORM8OgFBH9eADEpRHzGwalgVKYjIExoYPGawL+5sYY2iOdN9EzMa2r38WeK5LOgJRP3oFeg/VKe3TCF",
	"UGJQKgHfseYKZ7ZDwxe6zYAdzHNJNvtF/6bsTyqT8e/Gx+/MEKksmaEWVWw4syVqwaHLDPjaPI/UA9bP",
	"N/azy83nPSrYPJfkA2t+kCyzC5DWCYAXIN6uwFIHpfmPl1Mgl7YN6L+Y4DFKOLv5q6n3AbAtEqJGtoOp",
	"sFYpaJvnQWUqvJM0BXTGtbFTn3R1vBbs0NuUGfNd6biRFJaNQccAl9VNfQLYnb1Wm/2Xum51TYIy525M",
	"V1PnsRStnr5ChHt1uR81LROpuHttCRjD5nBcS5yh6t8lu9gzWtJZojLPktJ8M6GYrWyXL24bUOXCz5TH",
	"/TLwuoblyKAQ6Gy1TkDaKY6sHo1lNjOHFoF6cwuJ6b1TlpMxrdnaPfvUeQBNBzJtxwAlXw4R5FdgJtPg",
	"zPAgOYICMkvc+JRD5Kw01yyhAV1yoRziXAguuEXu+d/HDs77zapNvNxZ+yFawl8YvhcCKPrWQoKE5vLW",
	"D7poA+Jnz9HvM+u97+oC0IKnKZdzT6UjY+/zzp9d35Yn1UzSXPCOgrtCu+Cs1t4yfeq3tb6W/5Yxabld",
	"93HTnRXVJNXm2avufWn/gnksTbVaQYzkjZbgD+YsXk+tmjoj4OkZ/QxtJqcLJdy/iMkIhIB4PycH8qjL",
	"j4vUpGXixla1oTITgj0JKE7xLYV4wuYwxRJAAxLt3Pb4aDk1VkXLfoE0qRx9muWefmj1u4FhWxQpuuKU",
	"zuP8cTUKbpRloh6Z2D+x7y7L8l2xOWGxzmqZhXY1e3UxsSGqRsVYc7k0fl432UxnOGnCxRJjo4pAO/gD",
	"+sSWoNeOhUotfdNMqx8gXdMCEm4svl6s5xywzKP0nEkedZK1zEL70rVMmNuEbcSf+uJA8JXXOeXRMks7",
	"NaklZC3GczNdudc1WjwpJYDJFl5l17b5sYAnZ6rIIZl3rnxjpEzA0jAZMz3SbMmjv6/ZQqlRpJKqcnZV",
	"9iF3bMn/+x+0A7fOf+inm5+vrm8+X5GflIrJ/UKl5OrTLQ3oCrTxeeXFaDwa456QgmQppxP6HpsCLNHh",
	"YsMiVIeJivlsHW54vPUVWBst2oW/BwMxsYr43qQYTVKtZlzAiKI0jaa9jemE/oody4Q2aJR2v3TDX3UJ",
	"eUy3j/V64HofZxolw3C3bLdba/rLeLx/orxf2CrBbAN6Ob44PrDjbHM5ft93XHUkuRxfHh9U1gq2Af1r",
	"n2V1lXfwAJIlCdPrErQS3RG+rqiy8t4DIbI53OAPsmYOdj9nogVES8JnBPvnpS7CJYmZZU/MdLAn91O4",
	"KfO+IeTxzub5MxT7jtPga0H/w3Gc9vABj3Hv/M4YbvBpAC3S+qXCEHbgbcRv1eFxCEf89cQbR07lyFHQ",
	"kCq8Ojcf5IIGqzmsgOQDDJkpTSLQlnFZ7TY8bpPhLh9anm5PQbRV8n0teN7tGn6Ema0yhxxXA7NAJHwv",
	"RrVR+YB9igLCCRv5zkVYex+/aCvoheb27GGe2sXTy+P9tx55SHE7dUb/9diVuNW9tMwBB7kqOdlVT08K",
	"T3TvV+/dOd6qKGj1A5oJQXBId1Tej3NepDgFsZ0boFcHmLf3sGCMY/aFYl8BOiEQNz4OeAvDZw3DOWKV",
	"Uw4MwTim4ZS+5VDwLYjwQqG3eX/8Ov04Rzitaq39Ay9bMY61U5IPN/uhLetspwDVuoN+dVjtM3cdvHDG",
	"hQVdPL7DUm24wZ8BjpsPJzFYxoXfV6uvMdL6B4bH4b5eNyq+Q13bV5tP8+430gxCssGkYaG+n5xDgb8o",
	"qr9Y6N/9nOa1cyPH3/C5fJdfnh9M7YSaH0yzG9/G0v+jWN74uPatYj4E6192MKoQ9ndvhxHWMOfGgsb0",
	"/TjQd9jdv6DPcjnyls2flM0XRQ9dA2jk7wL9V60+0GZa0AldWJtOwlCoiImFMnbyfjwehyzl4QXe0TXN",
	"76WSWuOIbh+3/wsAAP//YXeYzTkxAAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
