// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Customer defines model for Customer.
type Customer struct {
	Email       string `json:"email"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Password    string `json:"password"`
	PhoneNumber string `json:"phone_number"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	Amount  float32 `json:"amount"`
	OrderId string  `json:"order_id"`
}

// Invoices defines model for Invoices.
type Invoices []Invoice

// Login defines model for Login.
type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// MeasurementUnit defines model for MeasurementUnit.
type MeasurementUnit string

// List of MeasurementUnit
const (
	MeasurementUnit_gram       MeasurementUnit = "gram"
	MeasurementUnit_kilo       MeasurementUnit = "kilo"
	MeasurementUnit_liter      MeasurementUnit = "liter"
	MeasurementUnit_milliliter MeasurementUnit = "milliliter"
	MeasurementUnit_piece      MeasurementUnit = "piece"
)

// Order defines model for Order.
type Order struct {
	CustomerId   string       `json:"customer_id"`
	OrderItems   []OrderItem  `json:"order_items"`
	OrderStatus  OrderStatus  `json:"order_status"`
	ShippingType ShippingType `json:"shipping_type"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	ProductId string  `json:"product_id"`
	Quantity  float32 `json:"quantity"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// List of OrderStatus
const (
	OrderStatus_approved      OrderStatus = "approved"
	OrderStatus_cancelled     OrderStatus = "cancelled"
	OrderStatus_invoiced      OrderStatus = "invoiced"
	OrderStatus_on_hold       OrderStatus = "on_hold"
	OrderStatus_packed        OrderStatus = "packed"
	OrderStatus_ready_to_ship OrderStatus = "ready_to_ship"
)

// Orders defines model for Orders.
type Orders []Order

// Product defines model for Product.
type Product struct {
	Description     *string          `json:"description"`
	ImagePath       *string          `json:"image_path"`
	InStock         float32          `json:"in_stock"`
	MeasurementUnit *MeasurementUnit `json:"measurement_unit,omitempty"`
	Name            string           `json:"name"`
	Price           float32          `json:"price"`
	ProductGroup    ProductGroup     `json:"product_group"`
}

// ProductGroup defines model for ProductGroup.
type ProductGroup string

// List of ProductGroup
const (
	ProductGroup_bakery    ProductGroup = "bakery"
	ProductGroup_chemistry ProductGroup = "chemistry"
	ProductGroup_cookies   ProductGroup = "cookies"
	ProductGroup_drinks    ProductGroup = "drinks"
	ProductGroup_frozen    ProductGroup = "frozen"
	ProductGroup_fruit     ProductGroup = "fruit"
	ProductGroup_groceries ProductGroup = "groceries"
	ProductGroup_hygiene   ProductGroup = "hygiene"
	ProductGroup_meat      ProductGroup = "meat"
	ProductGroup_milk      ProductGroup = "milk"
	ProductGroup_organic   ProductGroup = "organic"
)

// Products defines model for Products.
type Products []Product

// ShippingType defines model for ShippingType.
type ShippingType string

// List of ShippingType
const (
	ShippingType_delivery ShippingType = "delivery"
	ShippingType_pickup   ShippingType = "pickup"
)

// Validation defines model for Validation.
type Validation struct {
	IsValid bool `json:"is_valid"`
}

// Email defines model for email.
type Email openapi_types.Email

// Group defines model for group.
type Group string

// Id defines model for id.
type Id string

// Phone defines model for phone.
type Phone string

// BadRequest defines model for BadRequest.
type BadRequest Error

// Conflict defines model for Conflict.
type Conflict Error

// CustomerResponse defines model for CustomerResponse.
type CustomerResponse Customer

// InternalServerError defines model for InternalServerError.
type InternalServerError Error

// InvoiceResponse defines model for InvoiceResponse.
type InvoiceResponse Invoice

// InvoicesResponse defines model for InvoicesResponse.
type InvoicesResponse Invoices

// NotFound defines model for NotFound.
type NotFound Error

// OrderResponse defines model for OrderResponse.
type OrderResponse Order

// OrdersResponse defines model for OrdersResponse.
type OrdersResponse Orders

// ProductResponse defines model for ProductResponse.
type ProductResponse Product

// ProductsResponse defines model for ProductsResponse.
type ProductsResponse Products

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated Error

// Unauthorized defines model for Unauthorized.
type Unauthorized Error

// ValidationResponse defines model for ValidationResponse.
type ValidationResponse Validation

// CustomerLoginRequest defines model for CustomerLoginRequest.
type CustomerLoginRequest Login

// CustomerRequest defines model for CustomerRequest.
type CustomerRequest Customer

// InvoiceRequest defines model for InvoiceRequest.
type InvoiceRequest Invoice

// OrderRequest defines model for OrderRequest.
type OrderRequest Order

// ModifyCustomerRequestBody defines body for ModifyCustomer for application/json ContentType.
type ModifyCustomerJSONRequestBody CustomerRequest

// CreateInvoiceRequestBody defines body for CreateInvoice for application/json ContentType.
type CreateInvoiceJSONRequestBody InvoiceRequest

// CreateOrderRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody OrderRequest

// CustomerLoginRequestBody defines body for CustomerLogin for application/json ContentType.
type CustomerLoginJSONRequestBody CustomerLoginRequest

// CustomerRegistrationRequestBody defines body for CustomerRegistration for application/json ContentType.
type CustomerRegistrationJSONRequestBody CustomerRequest
