// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// Customer defines model for Customer.
type Customer struct {
	Email       string `json:"email"`
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Password    string `json:"password"`
	PhoneNumber string `json:"phone_number"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	Amount        float32       `json:"amount"`
	OrderId       string        `json:"order_id"`
	PaymentStatus PaymentStatus `json:"payment_status"`
	PaymentType   PaymentType   `json:"payment_type"`
}

// Invoices defines model for Invoices.
type Invoices []Invoice

// Login defines model for Login.
type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// MeasurmentUnit defines model for MeasurmentUnit.
type MeasurmentUnit string

// List of MeasurmentUnit
const (
	MeasurmentUnit_gram       MeasurmentUnit = "gram"
	MeasurmentUnit_kilo       MeasurmentUnit = "kilo"
	MeasurmentUnit_liter      MeasurmentUnit = "liter"
	MeasurmentUnit_milliliter MeasurmentUnit = "milliliter"
	MeasurmentUnit_piece      MeasurmentUnit = "piece"
)

// Order defines model for Order.
type Order struct {
	CustomerId   string       `json:"customer_id"`
	OrderItems   []OrderItem  `json:"order_items"`
	OrderStatus  OrderStatus  `json:"order_status"`
	ShippingType ShippingType `json:"shipping_type"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	ProductId string  `json:"product_id"`
	Quantity  float32 `json:"quantity"`
}

// OrderStatus defines model for OrderStatus.
type OrderStatus string

// List of OrderStatus
const (
	OrderStatus_approved      OrderStatus = "approved"
	OrderStatus_cancelled     OrderStatus = "cancelled"
	OrderStatus_invoiced      OrderStatus = "invoiced"
	OrderStatus_on_hold       OrderStatus = "on_hold"
	OrderStatus_packed        OrderStatus = "packed"
	OrderStatus_ready_to_ship OrderStatus = "ready_to_ship"
)

// Orders defines model for Orders.
type Orders []Order

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// List of PaymentStatus
const (
	PaymentStatus_canceled  PaymentStatus = "canceled"
	PaymentStatus_completed PaymentStatus = "completed"
	PaymentStatus_pending   PaymentStatus = "pending"
	PaymentStatus_refunded  PaymentStatus = "refunded"
)

// PaymentType defines model for PaymentType.
type PaymentType string

// List of PaymentType
const (
	PaymentType_cash            PaymentType = "cash"
	PaymentType_credit_card     PaymentType = "credit_card"
	PaymentType_debit_card      PaymentType = "debit_card"
	PaymentType_personal_cheque PaymentType = "personal_cheque"
	PaymentType_transfer        PaymentType = "transfer"
)

// Product defines model for Product.
type Product struct {
	Description    *string        `json:"description"`
	ImagePath      *string        `json:"image_path"`
	InStock        float32        `json:"in_stock"`
	MeasurmentUnit MeasurmentUnit `json:"measurment_unit"`
	Name           string         `json:"name"`
	Price          float32        `json:"price"`
	ProductGroup   ProductGroup   `json:"product_group"`
}

// ProductGroup defines model for ProductGroup.
type ProductGroup string

// List of ProductGroup
const (
	ProductGroup_bakery    ProductGroup = "bakery"
	ProductGroup_chemistry ProductGroup = "chemistry"
	ProductGroup_cookies   ProductGroup = "cookies"
	ProductGroup_drinks    ProductGroup = "drinks"
	ProductGroup_frozen    ProductGroup = "frozen"
	ProductGroup_fruit     ProductGroup = "fruit"
	ProductGroup_groceries ProductGroup = "groceries"
	ProductGroup_hygiene   ProductGroup = "hygiene"
	ProductGroup_meat      ProductGroup = "meat"
	ProductGroup_milk      ProductGroup = "milk"
	ProductGroup_organic   ProductGroup = "organic"
)

// Products defines model for Products.
type Products []Product

// ShippingType defines model for ShippingType.
type ShippingType string

// List of ShippingType
const (
	ShippingType_delivery ShippingType = "delivery"
	ShippingType_pickup   ShippingType = "pickup"
)

// Id defines model for id.
type Id string

// BadRequest defines model for BadRequest.
type BadRequest Error

// Conflict defines model for Conflict.
type Conflict Error

// CustomerResponse defines model for CustomerResponse.
type CustomerResponse Customer

// InternalServerError defines model for InternalServerError.
type InternalServerError Error

// InvoiceResponse defines model for InvoiceResponse.
type InvoiceResponse Invoice

// InvoicesResponse defines model for InvoicesResponse.
type InvoicesResponse Invoices

// NotFound defines model for NotFound.
type NotFound Error

// OrderResponse defines model for OrderResponse.
type OrderResponse Order

// OrdersResponse defines model for OrdersResponse.
type OrdersResponse Orders

// ProductResponse defines model for ProductResponse.
type ProductResponse Product

// ProductsResponse defines model for ProductsResponse.
type ProductsResponse Products

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated Error

// Unauthorized defines model for Unauthorized.
type Unauthorized Error

// CustomerLoginRequest defines model for CustomerLoginRequest.
type CustomerLoginRequest Login

// CustomerRequest defines model for CustomerRequest.
type CustomerRequest Customer

// OrderRequest defines model for OrderRequest.
type OrderRequest Order

// CustomerLoginRequestBody defines body for CustomerLogin for application/json ContentType.
type CustomerLoginJSONRequestBody CustomerLoginRequest

// CustomerRegistrationRequestBody defines body for CustomerRegistration for application/json ContentType.
type CustomerRegistrationJSONRequestBody CustomerRequest

// ModifyCustomerRequestBody defines body for ModifyCustomer for application/json ContentType.
type ModifyCustomerJSONRequestBody CustomerRequest

// CreateOrderRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody OrderRequest

